### ISSUE TITLE
Emulate "State: PV Input Signal Detected"

### ISSUE THREAD

**Issue by scoudibou** [tspopp/AquaMQTT#23]
Hello @tspopp ,

Do you think that it is possible to emulate the input of your newly added "State: PV Input Signal Detected" state ?
For now, it is working if you put an AC input or a dry contact to the power supply connector near the main supply (B1/B2 contact), it's switching to PV mode (450W treshold, going to 62°C to store energy) : 
![image](https://github.com/tspopp/AquaMQTT/assets/108148811/843eb0a9-1c3a-456a-a0eb-7370d83b7520)
But you need an external installation to do it : 
![image](https://github.com/tspopp/AquaMQTT/assets/108148811/888d9ab9-bc91-47f2-a130-32ec709a36c7)
The idea is to spare this installation to tell that the PV input is active even if there is nothing in the real PV input. So less wiring, less device... and using AquaMQTT to control virtually this input.
I know that you are in man in the middle mode between HMI and main board and that input is directly to main board but didn't you see this kind of info doing reverse engineering ? Normally there is the PV state that come to HMI with PV icon displayed but perhaps there is a way to control the PV mode from there ?

Regards,

**Comment by tspopp** [comment]
Since the "State: PV Input Signal Detected" is something entirely handled by the main controller, we are not able to change that state using the HMI controller, forcing the Main controller to act like a real hardware PV signal has been detected (through dry contact).

In MITM mode it would be technically possible, to tell the HMI that the AquaMQTT custom PV modes are active and therefore let the HMI display the PV icon? I think this one can be added very easily... :) Is that the suggested change?
