### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tukutt** [tspopp/AquaMQTT#51]
Hi Thomas,
It's not a bug ! But a request to update the documentation. I have a Thermor Aeromax 5.

I created an adapter so as not to cut the original cable.

You can find it here :
https://oshwlab.com/tukutt/aquamqtt-original-pcb-to-rast-co

Are you interesting in a PR to add this connector to the documentation ?

Some pictures :
- https://forum.hacf.fr/t/integration-dun-chauffe-eau-atlantic-explorer-en-mqtt/40493/44
- https://forum.hacf.fr/t/integration-dun-chauffe-eau-atlantic-explorer-en-mqtt/40493/58

Thanks

**Comment by tspopp** [comment]
Nice 🎉, sure let's add this! Do you have any other issues with the Thermor Airomax 5? Are the debugging stats values ok, so almost no dropped bytes in both HMI and Main channel?

Maybe you can also provide the software version shown in your HMI and Main Controller, since there is a new protocol version which is not yet supported. And I would love to determine at which version the current Aquamqtt implementation gets incompatible ;)
https://github.com/tspopp/AquaMQTT/issues/45#issuecomment-2440025043

**Comment by tukutt** [comment]
Thanks !

User Interface : E
Control : G

![image](https://github.com/user-attachments/assets/82eb5d3b-c255-42e3-ad88-99831ea2a88e)


![image](https://github.com/user-attachments/assets/154862c6-233e-4097-bfdf-97ef5552129c)

Just 1 byte drop when I started it.

tukutt

**Comment by tukutt** [comment]
Of course! Give me a few days to make the log.

**Comment by tukutt** [comment]
Sorry for the delay. This some debug log. I hope it helps you
[aquamqtt_hmi_debug_hex.csv](https://github.com/user-attachments/files/17707661/aquamqtt_hmi_debug_hex.csv)
[aquamqtt_hmi_debug_dec.csv](https://github.com/user-attachments/files/17707662/aquamqtt_hmi_debug_dec.csv)
[aquamqtt_main_debug_hex.csv](https://github.com/user-attachments/files/17707663/aquamqtt_main_debug_hex.csv)
[aquamqtt_main_debug_dec.csv](https://github.com/user-attachments/files/17707664/aquamqtt_main_debug_dec.csv)
